#! /bin/sh 

#This script is called by the rno-g-export-gpios service
# to export all of the relevant GIOS. It also will create symlinks for some of them. 


# LTE ENABLE GPIO (gpio 48) 
if [ ! -d /sys/class/gpio/gpio48 ]; then
	echo 48 > /sys/class/gpio/export
	ln -s /sys/class/gpio/gpio48 /dev/gpioENABLELTE 
fi

#echo 0 > /dev/gpioENABLELTE/value 
#echo out > /dev/gpioENABLELTE/direction 



# RADIANT MCU RESTART (gpio 89) 
if [ ! -d /sys/class/gpio/gpio89 ]; then
	echo 89 > /sys/class/gpio/export
	ln -s /sys/class/gpio/gpio89 /dev/gpioRADIANTMCURESET 
fi
#
#
#
# RADIANT SPI ENABLE

if [ ! -d /sys/class/gpio/gpio61 ]; then
	echo 61 > /sys/class/gpio/export
	ln -s /sys/class/gpio/gpio61 /dev/gpioRADIANTSPI 
fi

# SPI permissions
if [ ! -d /dev/spi ]; then
  mkdir /dev/spi
  ln -s /dev/spidev0.0 /dev/spi/0.0
  ln -s /dev/spidev1.0 /dev/spi/1.0
  ln -s /dev/spidev0.1 /dev/spi/0.1
  ln -s /dev/spidev1.1 /dev/spi/1.1
  chgrp gpio /dev/spidev*
  chmod 0660 /dev/spidev*
fi
